# Project: juego
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "../../../../Nueva\ carpetattt/Documentos/GitHub/proyecto/main.o"
LINKOBJ  = "../../../../Nueva carpetattt/Documentos/GitHub/proyecto/main.o"
LIBS     = -L"C:/Dev-Cpp/MinGW64/lib32" -L"C:/Dev-Cpp/lib" -L"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lm -lalleg -mwindows -lalleg -m32
INCS     = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Dev-Cpp/MinGW64/include" -I"C:/Dev-Cpp/include" -I"C:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "juego .exe"
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"../../../../Nueva\ carpetattt/Documentos/GitHub/proyecto/main.o": ../../../../Nueva\ carpetattt/Documentos/GitHub/proyecto/main.cpp
	$(CPP) -c "../../../../Nueva carpetattt/Documentos/GitHub/proyecto/main.cpp" -o "../../../../Nueva carpetattt/Documentos/GitHub/proyecto/main.o" $(CXXFLAGS)
